/**
 * GENERATED by scripts/build-fonts.py — do not edit by hand.
 *
 * The filenames carry a content hash so /fonts/* can be served immutable, which
 * means the preload in BaseLayout cannot be a hard-coded string.
 */

export const fontFiles = {
  /** Preloaded. Everything above the fold is set in it. */
  roman: '/fonts/eagle-span-sans-roman-var.25d6665e4a.woff2',
  /** Not preloaded — only downloads if a page actually renders italic text. */
  italic: '/fonts/eagle-span-sans-italic-var.5085f59d89.woff2',
} as const;
